name: pomeranian_chrome
description: A sample Chrome packaged application
dependencies:
  browser: '>=0.10.0 <0.11.0'
  chrome: '>=0.6.0 <0.7.0'
  core_elements: '>=0.2.0 <0.3.0'
  paper_elements: 'any'
  polymer: '>=0.14.0 <0.15.0'
  rikulo_gap: '>=0.6.0 <0.7.0'
dev_dependencies:
  http: any
transformers:
- polymer:
    entry_points: web/pomeranianchrome.html
    csp: true
    inject_build_logs_in_output: false
- $dart2js:
    csp: true
