name: pomeranian_chrome
description: A sample Chrome packaged application
dependencies:
  browser: any
  chrome: any
  core_elements: any
  paper_elements: any
  polymer: any
transformers:
- pomeranian_chrome/transformer :
    entry_points: web/pomeranianchrome.html
    csp: true
    inject_build_logs_in_output: false